name: Build and Release APK

on:
  push:
    branches:
      - master  # Change this to match your branch, or add more branches as needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Install Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.10.0'  # Specify the Flutter version you are using

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          files: build/app/outputs/flutter-apk/app-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
