name: Build and Release APK

on:
  push:
    branches:
      - master  # Change this to match your branch, or add more branches as needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Install Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.16.9'

      - name: Build APK
        run: flutter build apk --release

      - name: Create and Push Tag
        uses: mathieudutour/github-tag-action@v5.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ github.sha }}  # This will use the commit SHA as a tag, but you can customize it
          create_annotated_tag: true

      - name: Upload APK to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          files: build/app/outputs/flutter-apk/app-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
